@extends('layaut.app')
@section('nav')
    @include('partes.nav')
@endsection
@section('conten')
    @include('partes.insprograms')
@endsection
@section('logo')
    @include('partes.logo')
@endsection