@extends('layaut.app')
@section('nav')
    @include('partes.nav')
@endsection
@section('conten')
    @include('partes.programs')
@endsection
@section('logo')
    @include('partes.logo')
@endsection
@section('login')
    @include('partes.login')
@endsection