@extends('layaut.app')
@section('nav')
    @include('partes.navadm')
@endsection
@section('conten')
    @include('partes.register-course')
@endsection
@section('logo')
    @include('partes.logo')
@endsection
@section('login')
    @include('partes.admin1')
@endsection
