@extends('layaut.app')
@section('logo')
    @include('partes.logo')
    @endsection
@section('nav')
    @include('partes.navadm')
    @endsection
@section('conten')
    @include('partes.register-affiliated-action')
    @endsection
@section('login')
    @include('partes.admin1')
    @endsection
