@extends('layaut.app')
@section('nav')
    @include('partes.nav')
@endsection
@section('conten')
    @include('partes.reserve-sports-equipment')
@endsection
@section('nav')
    @include('partes.logo-usericons')
@endsection
@section('logo')
    @include('partes.logo')
@endsection